### PR TITLE
Address a real defect, use GenConfig without generated symlink version tracking, improve maintainability, improve readability of STDOUT

### PR DESCRIPTION
**Pull request by bartlettroscoe**
@e10harvey, please review the individual commits to see about the changes.  There is one real defect fixed in commit  https://github.com/bartlettroscoe/Trilinos/commit/bc80cdf57d5256c96f3f51a0b18f239c520b46da.  The rest of the commits (arguably) improve the maintainability of the script or the readability of STDOUT.  I also updated the GenConfig SHA1 in commit https://github.com/bartlettroscoe/Trilinos/commit/7539df23b0429170afada416b9deb06683886eb3 to no longer track symlinks.

Please review the individual commits and try this out yourself.

Otherwise, I think this is the ticket (until you can create the TrilinosCITools repo as we discussed).

### CODE REVIEW

**Review by e10harvey — APPROVED** [review]
Thanks for your help, Ross!

I pushed one more commit to add `STATUS: ` and `INFO: ` to some of the print statements.

I also added a detailed story on our backlog for moving to TrilinosCiUtils.

**Comment by bartlettroscoe** [comment]
@e10harvey, we were supposed to merge this staggered PR into PR #10620 before merging #10620 into 'develop'.  But I can just change the target branch of this PR to the main repo 'develop' branch and we can approve and merge that again.  (But will need to wait for PR testing to approve.)

In the future, I will push branches to the main Trilinos GitHub repo if I think there is a good chance of needing to post staged PRs (so the staged PRs can appear in the main GitHub repo as well).

**Comment by bartlettroscoe** [comment]
Shoot, GitHub will not let me change the target branch.  Therefore, I will have to close this PR and open a new PR against the main repo 'develop' branch.

**Comment by bartlettroscoe** [comment]
FY: The new PR is https://github.com/trilinos/Trilinos/pull/10643.

**Pull request closed without merging**
