### PR TITLE
Add unit test for thread safe RCP.

### PR DESCRIPTION
**Pull request by d-meiser**
This test modifies the ref count of a RCP concurrently from several
threads.  A thread safe implementation yields the correct reference
count after all threads have `join`ed.

@bartlettroscoe this is wip but I wanted to share now because I'm getting a runtime error that you may be able to help with. When I run this test case I get an error message from the C++ runtime: `Enable multithreading to use std::thread: Operation not permitted`.

My question is: Is there anything Trilinos specific that I need to do at configure, build, or runtime to enable threads:
## Additional details:

The full error message is:

```
[dmeiser@ivyamd MemoryManagement]$ ./TeuchosCore_MemoryManagement_MT_UnitTests.exe 
Teuchos::GlobalMPISession::GlobalMPISession(): started serial run

***
*** Unit test suite ...
***


Sorting tests by group name then by the order they were added ... (time = 2e-06)

Running unit tests ...

0. RCP_mtRefCount_UnitTest ... 
 ptr.total_count() == 1 = 1 == true : passed

 p=0: *** Caught standard std::exception of type 'std::system_error' :

  Enable multithreading to use std::thread: Operation not permitted
 [FAILED]  (0.000242 sec) RCP_mtRefCount_UnitTest
 Location: /scr_ivyamd/dmeiser/Trilinos/packages/teuchos/core/test/MemoryManagement/RCP_MT_UnitTests.cpp:82


The following tests FAILED:
    0. RCP_mtRefCount_UnitTest ... 

Total Time: 0.000425 sec

Summary: total = 1, run = 1, passed = 0, failed = 1

End Result: TEST FAILED

```

This is with gcc 4.9.3. Recompiling by hand with `-pthread -Wl,--no-as-needed` added to the compile line does not help (see e.g. this discussion http://stackoverflow.com/questions/19463602/compiling-multithread-code-with-g).

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
Looks like we need to link against the pthread library:

http://stackoverflow.com/questions/17274032/c-threads-stdsystem-error-operation-not-permitted

Looks like we need to add `Pthread` to `LIB_OPTIONAL_TPLS` list in the file:

```
Trilinos/packages/teuchos/core/cmake/Dependencies.cmake
```

and then we should also add:

```
TRIBITS_TPL_TENTATIVELY_ENABLE(Pthread)
```

to the end of that file so that it gets enabled by default.

We can figure out the rest of the implications later once we get these tests written and passing on the branch.

**Comment by d-meiser** [comment]
Sounds good. I'll make those changes. Will let you know how it goes ...

**Comment by d-meiser** [comment]
With pthreads enabled the tests work. However, apparently pthreads is disabled for `checkin-test.py`'s default builds. For `--st-extra-builds=SERIAL_DEBUG` pthreads get added to the TPLs. In `checkin-test.py` I see the comment

```
NOTE: All tentatively-enabled TPLs (e.g. Pthreads and BinUtils) are hard
disabled in order to avoid different behaviors between machines where they
would be enabled and machines where they would be disabled.
```

This makes sense to me because we want the tests to be reproducible. What's the best way to move forward here?

**Comment by bartlettroscoe** [comment]
Right now we can't allow Pthread to be a required Primary Tested (PT) TPL or every Trilinos developer will need to have Pthreads on their machine.  We are likely going to expand the set of Primary Tested Packages and TPLs for Trilinos but that has not happened yet.

For now, you will need to add a new ST build to allow Pthread to be enabled.  You can define an extra build something like `SERIAL_DEBUG_MT`.  You can write a quick wrapper script for checkin-test.py like:

```
$ cat checkin-test-mt.sh
#!/bin/bash -e

if [ "$TRILINOS_DIR" == "" ] ; then
  TRILINOS_DIR=../../Trilinos
fi
TRILINOS_DIR_ABS=$(readlink -f $TRILINOS_DIR)

echo "
-DTPL_ENABLE_MPI=OFF
-DCMAKE_BUILD_TYPE=DEBUG
-DCMAKE_C_COMPILER=gcc
-DTPL_ENABLE_Pthread=ON
" > SERIAL_DEBUG_MT.config

$TRILINOS_DIR_ABS/checkin-test.py \
--st-extra-builds=SERIAL_DEBUG_MT \
-j12 \
"$@"
```

Then if you only wanted to run that build, do (assuming standard directory structure):

```
$ cd <some-base>/BUILDS/CHECKIN/
$ ./checkin-test-mt.sh --default-builds=  \
  --no-enable-fwd-packages --enable-packages=TeuchosCore \
  --local-do-all
```

Note that the checkin-test.py script is really designed to test changes and push to the shared branch.  A more efficient iterative development workflow is typically to create a [do-configure script](https://trilinos.org/docs/files/TrilinosBuildReference.html#basic-configuration) locally and then just type .`/do-configure` followed by `make -j12` and `ctest -j12`.  But it is really up to you how you want to do your development workflow.

**Comment by d-meiser** [comment]
@bartlettroscoe this all makes sense, thanks a lot for the info.

I think I've got the local testing and development under control. I'll amend this PR shortly with a possible path forward to make this mergeable without breaking tests.

**Comment by bartlettroscoe** [comment]
We don't need to worry about integrating into the master branch right now.  We can just focus on getting the functionality to work and demonstrate and protected this with good automated tests.  In any case, before this can be merged, we will also need to make this conditional on C++11 support.  There is one Trilinos customer who can't use C++11 on one platform (they have an old MS VC++ compiler) and therefore we have to keep Teuchos working with C++98/03 for now.  When C++11 is not enabled, then the Teuchos MM classes will not be threadsafe.  But that is just fine with this one customer.

To make the C++11 dependence/thread safety conditional, we will create some simple template abstractions and then at configure time, choose one or the other.  We don't want to do this with a lot of ifdefs sprinkled throughout the code. We can take care of that at the very end.  It will be easy to come up with the abstraction after we get everything working.

**Pull request closed without merging**
